# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: brain-tumor-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: brain-tumor-app
#   template:
#     metadata:
#       labels:
#         app: brain-tumor-app
#     spec:
#       containers:
#       - name: brain-tumor-app
#         image: 275115135612.dkr.ecr.us-east-1.amazonaws.com/brain-tumor-classifier:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8000
#         env:
#         - name: PYTHONUNBUFFERED
#           value: "1"
#         resources:
#           requests:
#             memory: "2Gi"
#             cpu: "1000m"
#           limits:
#             memory: "6Gi"
#             cpu: "1800m"
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: 8000
#           initialDelaySeconds: 30
#           periodSeconds: 30
#         readinessProbe:
#           httpGet:
#             path: /health
#             port: 8000
#           initialDelaySeconds: 30
#           periodSeconds: 15
#         startupProbe:
#           httpGet:
#             path: /health
#             port: 8000
#           initialDelaySeconds: 60
#           periodSeconds: 10
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: brain-tumor-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: brain-tumor-app
#   ports:
#     - port: 80
#       targetPort: 8000
